desc <<-DESC
Updates the versions of the native libraries.

#### Options
* `version`: The version of the native libraries.
* `platform`: The platform to update. Leave blank to update both.

#### Examples
```sh
bundle exec fastlane update_native_libraries version:3.4.0
bundle exec fastlane update_native_libraries version:3.4.0 platform:android
bundle exec fastlane update_native_libraries version:3.4.0 platform:ios
```
DESC
lane :update_native_libraries do |options|
  version = options[:version]
  platform = options[:platform]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  if platform.nil? || platform.downcase == 'android'
    UI.message('Updating native Android libraries.')
    update_native_android_libraries(version)
  end

  if platform.nil? || platform.downcase == 'ios'
    UI.message('Updating native iOS libraries.')
    update_native_ios_libraries(version)
  end
end

desc <<-DESC
#### Examples
```sh
bundle exec fastlane clear
```
DESC
lane :clear do |options|
  dry_run = options[:dry_run] ||= true

  if dry_run
    directories = Dir["../packages/*"]

    directories.each do |directory|
      UI.message("Validating '#{directory}' package.")
      stream_shell_command("cd #{directory} && rm -rf dist && rm -rf node_modules && cd android && rm -rf build")
    end

    next # skip doing the rest of this lane
  end
end

desc <<-DESC
Updates Kotlin version of each package.

#### Options
* `version`: The new version for Kotlin.

#### Examples
```sh
bundle exec fastlane update_kotlin_version version:1.7.20
```
DESC
lane :update_kotlin_version do |options|
  version = options[:version]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  files = Dir['../packages/capacitor-actito*/android/build.gradle']
  regex = /classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:.*'/
  replacement = "classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:#{version}'"

  files.each { |file| update_file(file, regex, replacement) }
end

desc <<-DESC
Updates the version of each package.

#### Options
* `version`: The new version for the libraries.

#### Examples
```sh
bundle exec fastlane bump version:3.4.0
```
DESC
lane :bump do |options|
  version = options[:version]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  # Lerna version
  files = Dir['../lerna.json']
  regex = /"version": ".*",/
  replacement = "\"version\": \"#{version}\","
  files.each { |file| update_file(file, regex, replacement) }

  # Package version
  files = Dir['../packages/capacitor-actito*/package.json']
  regex = /"version": ".*",/
  replacement = "\"version\": \"#{version}\","
  files.each { |file| update_file(file, regex, replacement) }

  # Package core dependencies
  files = Dir['../packages/capacitor-actito*/package.json']
  regex = /"capacitor-actito": ".*"/
  replacement = "\"capacitor-actito\": \"#{version}\""
  files.each { |file| update_file(file, regex, replacement) }
end

desc <<-DESC
Updates the lockfile of each package and sample app pods.

#### Examples
```sh
bundle exec fastlane update_sample
```
DESC
lane :update_sample do
  UI.message('Bootstrapping packages.')
  bootstrap_packages

  ios_dir = "../packages/sample/ios/App"
  podfile_path = File.join(ios_dir, "Podfile")

  if File.exist?(podfile_path)
    UI.message('Updating Cocoapods repo.')
    update_pod_repo

    UI.message('Updating app pods.')
    update_pods
  else
    UI.message('No Podfile found. Skipping Cocoapods steps.')
  end

  UI.message('Updating app SPM.')
  update_sample_spm_dependency

  UI.message('Clean DerivedData.')
  stream_shell_command("cd #{ios_dir} && rm -rf DerivedData")
end

desc <<-DESC
Validates and publishes each package.

#### Options
* `dry_run`: Only run in validation mode.

#### Examples
```sh
bundle exec fastlane publish
bundle exec fastlane publish dry_run:true
```
DESC
lane :publish do |options|
  dry_run = options[:dry_run] ||= false

  if dry_run
    directories = Dir["../packages/capacitor-actito*"]

    directories.each do |directory|
      UI.message("Validating '#{directory}' package.")
      stream_shell_command("cd #{directory} && npm publish --dry-run")
    end

    next # skip doing the rest of this lane
  end

  ensure_git_status_clean unless dry_run

  UI.message("Publishing packages.")
  stream_shell_command("lerna publish from-package")
end


def update_file(path, regex, replacement)
  file = File.read(path)
  new_content = file.gsub(regex, replacement)
  File.open(path, 'w') { |line| line.puts new_content }
end

def update_native_android_libraries(version)
  files = Dir['../packages/capacitor-actito*/android/build.gradle']
  regex = /def actito_version = '.*'/
  replacement = "def actito_version = '#{version}'"

  files.each { |file| update_file(file, regex, replacement) }
end

def update_native_ios_libraries(version)
  UI.message('Updating native iOS podspec files.')
  update_native_ios_podspec_files(version)

  UI.message('Updating native iOS SPM files.')
  update_native_ios_spm_files(version)
end

def update_native_ios_podspec_files(version)
  files = Dir['../packages/capacitor-actito*/*.podspec']
  regex = /actito_version = '.*'/
  replacement = "actito_version = '#{version}'"
  files.each { |file| update_file(file, regex, replacement) }
end

def update_native_ios_spm_files(version)
  files = Dir['../packages/capacitor-actito*/Package.swift']
  regex = /
    (\.package\(
      \s*url:\s*"https:\/\/github\.com\/Actito\/actito-sdk-ios\.git",
      \s*from:\s*")([^"]+)
      ("\s*\),?)
  /x

  replacement = "\\1#{version}\\3"
  files.each { |file| update_file(file, regex, replacement) }
end

def bootstrap_packages
  stream_shell_command("lerna clean -y")
  stream_shell_command("lerna bootstrap")
  stream_shell_command("cd ../packages/sample && ionic cap sync")
end

def update_pod_repo
  stream_shell_command("cd ../packages/sample/ios/App && pod repo update")
end

def update_pods
  stream_shell_command("cd ../packages/sample/ios/App && pod update")
end

def update_sample_spm_dependency
  package_swift_path = "../packages/capacitor-actito/Package.swift"
  ios_project_path = "../packages/sample/ios/App/App.xcodeproj"
  dependency_url = "https://github.com/Actito/actito-sdk-ios.git"

  new_version = get_spm_dependency_version(package_swift_path, dependency_url)
  UI.message("Updating Sample's Actito SPM dependency to: #{new_version}")

  project = Xcodeproj::Project.open(ios_project_path)
  spm_ref = project
                .objects
                .select { |o| o.is_a?(Xcodeproj::Project::Object::XCRemoteSwiftPackageReference) }
                .find { |p| p.repositoryURL.downcase == dependency_url.downcase }

  unless spm_ref
    UI.important("⚠️ SPM package #{dependency_url} not found in Xcode project #{ios_project_path}. Skipping update.")
    return
  end

  spm_ref.requirement = {
    'kind' => 'exactVersion',
    'version' => new_version
  }

  project.save

  UI.success("Updated #{dependency_url} → #{new_version}")
end

def get_spm_dependency_version(package_swift_path, dependency_url)
  content = File.read(package_swift_path)

  regex = /
    \.package\s*\(
      [^\)]*
      url:\s*"#{Regexp.escape(dependency_url)}"
      [^\)]*
      from:\s*"([^"]+)"
  /mx

  match = content.match(regex)

  UI.user_error!("SPM version not found for dependency: #{dependency_url}") unless match

  match[1]
end

def stream_shell_command(command)
  success = IO.popen(command) do |io|
    while line = io.gets
      puts line.chomp
    end

    io.close

    $?.success?
  end

  UI.user_error!("Failed to execute shell script '#{command}'") unless success
end
