desc <<-DESC
Updates the versions of the native libraries.

#### Options
* `version`: The version of the native libraries.
* `platform`: The platform to update. Leave blank to update both.

#### Examples
```sh
bundle exec fastlane update_native_libraries version:3.4.0
bundle exec fastlane update_native_libraries version:3.4.0 platform:android
bundle exec fastlane update_native_libraries version:3.4.0 platform:ios
```
DESC
lane :update_native_libraries do |options|
  version = options[:version]
  platform = options[:platform]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  if platform.nil? || platform.downcase == 'android'
    UI.message('Updating native Android libraries.')
    update_native_android_libraries(version)
  end

  if platform.nil? || platform.downcase == 'ios'
    UI.message('Updating native iOS libraries.')
    update_native_ios_libraries(version)
  end
end

desc <<-DESC
#### Examples
```sh
bundle exec fastlane clear
```
DESC
lane :clear do |options|
  dry_run = options[:dry_run] ||= true

  if dry_run
    directories = Dir["../packages/*"]

    directories.each do |directory|
      UI.message("Validating '#{directory}' package.")
      stream_shell_command("cd #{directory} && rm -rf dist && rm -rf node_modules && cd android && rm -rf build")
    end

    next # skip doing the rest of this lane
  end
end

desc <<-DESC
Updates Kotlin version of each package.

#### Options
* `version`: The new version for Kotlin.

#### Examples
```sh
bundle exec fastlane update_kotlin_version version:1.7.20
```
DESC
lane :update_kotlin_version do |options|
  version = options[:version]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  files = Dir['../packages/capacitor-actito*/android/build.gradle']
  regex = /classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:.*'/
  replacement = "classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:#{version}'"

  files.each { |file| update_file(file, regex, replacement) }
end

desc <<-DESC
Updates the version of each package.

#### Options
* `version`: The new version for the libraries.

#### Examples
```sh
bundle exec fastlane bump version:3.4.0
```
DESC
lane :bump do |options|
  version = options[:version]

  if version.nil?
    UI.user_error!("Missing required 'version' parameter.")
  end

  # Lerna version
  files = Dir['../lerna.json']
  regex = /"version": ".*",/
  replacement = "\"version\": \"#{version}\","
  files.each { |file| update_file(file, regex, replacement) }

  # Package version
  files = Dir['../packages/capacitor-actito*/package.json']
  regex = /"version": ".*",/
  replacement = "\"version\": \"#{version}\","
  files.each { |file| update_file(file, regex, replacement) }

  # Package core dependencies
  files = Dir['../packages/capacitor-actito*/package.json']
  regex = /"capacitor-actito": ".*"/
  replacement = "\"capacitor-actito\": \"#{version}\""
  files.each { |file| update_file(file, regex, replacement) }
end

desc <<-DESC
Updates the lockfile of each package, and sample apps iOS dependencies (SPM & Pods).

#### Examples
```sh
bundle exec fastlane update_sample_apps
```
DESC
lane :update_sample_apps do
  package_swift_path = "../packages/capacitor-actito/Package.swift"
  dependency_url = "https://github.com/Actito/actito-sdk-ios.git"
  dependency_version = get_spm_dependency_version(package_swift_path, dependency_url)

  UI.message('Bootstrapping packages for all modules and sample apps.')
  bootstrap_packages

  UI.message('Updating Sample Pods and SPM.')
  update_sample_app(dependency_url, dependency_version)

  UI.message('Updating Sample User Inbox Pods and SPM.')
  update_sample_user_inbox_app(dependency_url, dependency_version)
end

def update_sample_app(dependency_url, dependency_version)
  sample_ios_path = "../packages/sample/ios/App"
  sample_ios_project_path = "../packages/sample/ios/App/App.xcodeproj"
  podfile_path = File.join(sample_ios_path, "Podfile")

  if File.exist?(podfile_path)
    UI.message('Updating Sample ActitoNotificationServiceExtensionKit pod.')
    update_pod_notification_service_extension(sample_ios_path, dependency_version)

    UI.message('Updating Sample Cocoapods repo.')
    update_pod_repo(sample_ios_path)

    UI.message('Updating Sample app pods.')
    update_pods(sample_ios_path)
  else
    UI.important("No Podfile found for #{sample_ios_path}. Skipping Cocoapods steps.")
  end

  UI.message('Updating Sample SPM.')
  update_project_spm_dependency(sample_ios_project_path, dependency_url, dependency_version)
end

def update_sample_user_inbox_app(dependency_url, dependency_version)
  sample_user_inbox_ios_path = "../packages/sample-user-inbox/ios/App"
  sample_user_inbox_ios_project_path = "../packages/sample-user-inbox/ios/App/App.xcodeproj"
  podfile_path = File.join(sample_user_inbox_ios_path, "Podfile")

  if File.exist?(podfile_path)
    UI.message('Updating Sample User Inbox ActitoNotificationServiceExtensionKit pod.')
    update_pod_notification_service_extension(sample_user_inbox_ios_path, dependency_version)

    UI.message('Updating Sample User Inbox Cocoapods repo.')
    update_pod_repo(sample_user_inbox_ios_path)

    UI.message('Updating Sample User Inbox app pods.')
    update_pods(sample_user_inbox_ios_path)
  else
    UI.important("No Podfile found for #{sample_user_inbox_ios_path}. Skipping Cocoapods steps.")
  end

  UI.message('Updating Sample User Inbox SPM.')
  update_project_spm_dependency(sample_user_inbox_ios_project_path, dependency_url, dependency_version)
end

desc <<-DESC
Validates and publishes each package.

#### Options
* `dry_run`: Only run in validation mode.

#### Examples
```sh
bundle exec fastlane publish
bundle exec fastlane publish dry_run:true
```
DESC
lane :publish do |options|
  dry_run = options[:dry_run] ||= false

  if dry_run
    directories = Dir["../packages/capacitor-actito*"]

    directories.each do |directory|
      UI.message("Validating '#{directory}' package.")
      stream_shell_command("cd #{directory} && npm publish --dry-run")
    end

    next # skip doing the rest of this lane
  end

  ensure_git_status_clean unless dry_run

  UI.message("Publishing packages.")
  stream_shell_command("lerna publish from-package")
end


def update_file(path, regex, replacement)
  file = File.read(path)
  new_content = file.gsub(regex, replacement)
  File.open(path, 'w') { |line| line.puts new_content }
end

def update_native_android_libraries(version)
  files = Dir['../packages/capacitor-actito*/android/build.gradle']
  regex = /def actito_version = '.*'/
  replacement = "def actito_version = '#{version}'"

  files.each { |file| update_file(file, regex, replacement) }
end

def update_native_ios_libraries(version)
  UI.message('Updating native iOS podspec files.')
  update_native_ios_podspec_files(version)

  UI.message('Updating native iOS SPM files.')
  update_native_ios_spm_files(version)
end

def update_native_ios_podspec_files(version)
  files = Dir['../packages/capacitor-actito*/*.podspec']
  regex = /actito_version = '.*'/
  replacement = "actito_version = '#{version}'"
  files.each { |file| update_file(file, regex, replacement) }
end

def update_native_ios_spm_files(version)
  files = Dir['../packages/capacitor-actito*/Package.swift']
  regex = /
    (\.package\(
      \s*url:\s*"https:\/\/github\.com\/Actito\/actito-sdk-ios\.git",
      \s*from:\s*")([^"]+)
      ("\s*\),?)
  /x

  replacement = "\\1#{version}\\3"
  files.each { |file| update_file(file, regex, replacement) }
end

def bootstrap_packages
  stream_shell_command("lerna clean -y")
  stream_shell_command("lerna bootstrap")
  stream_shell_command("cd ../packages/sample && ionic cap sync")
end

def update_pod_repo(ios_path)
  stream_shell_command("cd #{ios_path} && pod repo update")
end

def update_pods(ios_path)
  stream_shell_command("cd #{ios_path} && pod update")
end

def update_pod_notification_service_extension(ios_path, version)
  podfile = "#{ios_path}/Podfile"

  regex = /
    (pod\s+['"]Actito\/ActitoNotificationServiceExtensionKit['"]\s*,\s*['"])
    ([^'"]+)
    (['"])
  /x

  content = File.read(podfile)
  match = content.match(regex)

  unless match
    UI.important("ActitoNotificationServiceExtensionKit pod not found in #{podfile}, skipping update.")
    return
  end

  current_version = match[2]

  if current_version == version
    UI.message("ActitoNotificationServiceExtensionKit in #{podfile} already at version #{version}, skipping update.")
    return
  end

  replacement = "\\1#{version}\\3"
  update_file(podfile, regex, replacement)

  UI.message("ActitoNotificationServiceExtensionKit updated from #{current_version} → #{version}")
end

def update_project_spm_dependency(ios_project_path, dependency_url, version)
  UI.message("Updating Actito SPM dependency in #{ios_project_path} to: #{version}")

  project = Xcodeproj::Project.open(ios_project_path)
  spm_ref = project
                .objects
                .select { |o| o.is_a?(Xcodeproj::Project::Object::XCRemoteSwiftPackageReference) }
                .find { |p| p.repositoryURL.downcase == dependency_url.downcase }

  unless spm_ref
    UI.important("⚠️ SPM package #{dependency_url} not found in Xcode project #{ios_project_path}. Skipping update.")
    return
  end

  spm_ref.requirement = {
    'kind' => 'exactVersion',
    'version' => version
  }

  project.save

  UI.success("Updated #{dependency_url} → #{version}")
end

def get_spm_dependency_version(package_swift_path, dependency_url)
  content = File.read(package_swift_path)

  regex = /
    \.package\s*\(
      [^\)]*
      url:\s*"#{Regexp.escape(dependency_url)}"
      [^\)]*
      from:\s*"([^"]+)"
  /mx

  match = content.match(regex)

  UI.user_error!("SPM version not found for dependency: #{dependency_url}") unless match

  match[1]
end

def stream_shell_command(command)
  success = IO.popen(command) do |io|
    while line = io.gets
      puts line.chomp
    end

    io.close

    $?.success?
  end

  UI.user_error!("Failed to execute shell script '#{command}'") unless success
end
